version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}
          - node-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  